spring:
  application:
    name: offline-first
  profiles:
    active: ${APP_PROFILE:custom}
  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: page
        size-parameter: size
        one-indexed-parameters: true
      sort:
        sort-parameter: sort
    mongodb:
      auto-index-creation: false
  main:
    allow-bean-definition-overriding: true
jwt:
  issuer: offline-first
server:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}
  port: ${SERVER_PORT:8080}