spring:
  data:
    mongodb:
      host: localhost:27017
      database: offline-first
  servlet:
    context-path: /api
jwt:
  public-key: classpath:app.pub
  private-key: classpath:app.key
  expiration:
    days: 365
  refresh:
    expiration: 365
logging:
#  file:
#    name: logs/orcamento.log
  include-application-name: false
  pattern:
    dateformat: "dd-MM-yyyy HH:mm:ss.SSS"
    console: "[%clr(${PID:}){cyan}] -%clr(${LOG_LEVEL_PATTERN:%5p}) - %d{HH:mm:ss.SSS} - %msg%n"
  level:
    feign: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: off
springdoc:
  show-login-endpoint: true
  api-docs:
    enabled: true
